### ISSUE TITLE
is there any difference with paper ATVGnet in landmark preprocess?

### ISSUE THREAD

**Issue by lianDaniel** [eeskimez/Talking-Face-Landmarks-from-Speech#3]

**Comment by eeskimez** [comment]
This is the old version of the landmark normalization. In this version, the landmark alignment is achieved by selecting fixed points in the image domain and applying a similarity transform calculated by those points. You can check the paper for more information on this. In the new version of our project (http://www2.ece.rochester.edu/projects/air/projects/3Dtalkingface.html), we use Procrustes analysis to align the landmarks.  The ATVGnet project uses the new version. You can use the normalization function provided in ATVGnet Github page to improve the results of this project. The new version of our project will be available in the upcoming months.
