### ISSUE TITLE
'generator' object has no attribute 'next'

### ISSUE THREAD

**Issue by XinCynthia** [eeskimez/Talking-Face-Landmarks-from-Speech#6]
Hi, when I run train.py, there is an error 'generator' object has no attribute 'next', could you tell me how to fix it? how to write the attribute 'next'? Thank you very much!

**Comment by interactivetech** [comment]
Hi @XinCynthia , I ran into the same issue. I resolved it by chaning `gen.next()` to `next(gen)`.

From this [tutorial](https://realpython.com/introduction-to-python-generators/):
```
you can also call next() on the generator object directly.
```

**Comment by sdulyq** [comment]
In fact  python2.x may get more good expections
