### ISSUE TITLE
vid.get_length() OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by interactivetech** [eeskimez/Talking-Face-Landmarks-from-Speech#7]
Hi there, 

Thanks for open sourcing this great project! I get the following error in line 76 in `featureExtractor.py` that: 
  
```
File "/home/Talking-Face-Landmarks-from-Speech/featureExtractor.py", line 76, in <module>
    for frm_cnt in tqdm(range(0, int(vid.get_length()))):
OverflowError: cannot convert float infinity to integer
```

According to this  [Stackoverflow Post](https://stackoverflow.com/questions/54778001/how-to-to-tackle-overflowerror-cannot-convert-float-infinity-to-integer), `vid.get_length()` is deprecated and will always returns `inf`.

If you are using `imageio >=2.5.0` The solution to this issue is to change `vid.get_length()` to `vid.count_frames()` will get the actual number of frames. 

I hope this helps anyone else using this repo in the future!

**Comment by eeskimez** [comment]
Thank you @interactivetech!

**Comment by interactivetech** [comment]
No problem! :)
