### ISSUE TITLE
generate.py

### ISSUE THREAD

**Issue by fiendwbc** [eeskimez/Talking-Face-Landmarks-from-Speech#8]
Hi
I run the .py successfully and it shows 
Using TensorFlow backend.
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         (None, 75, 768)           0
_________________________________________________________________
lstm_1 (LSTM)                (None, 75, 512)           2623488
_________________________________________________________________
lstm_2 (LSTM)                (None, 75, 512)           2099200
_________________________________________________________________
lstm_3 (LSTM)                (None, 75, 512)           2099200
_________________________________________________________________
lstm_4 (LSTM)                (None, 75, 136)           353056
=================================================================
Total params: 7,174,944
Trainable params: 7,174,944
Non-trainable params: 0

But nothing in the result folder.
Could you help me how to fix it?

**Comment by eeskimez** [comment]
Hi @fiendwbc, 

Are you using the exact versions of the Python libraries listed in the description? 

Can you try printing out the predicted vectors to see if they are empty?

Also, please make sure the speech file is loaded correctly. You can print out the shape of the sound variable on line 57 in the "generate.py" file. 

Thanks!

**Comment by DatGuy1** [comment]
@eeskimez You have exit() call [here](https://github.com/eeskimez/Talking-Face-Landmarks-from-Speech/blob/master/generate.py#L48)

**Comment by eeskimez** [comment]
@DatGuy1 thanks for solving the issue! Fixed it.

Closing this...
